 source 'http://rubygems.org'


gem 'appium_lib', '9.17.0'
gem 'creek', '2.4.1'
gem 'cucumber', '3.1.2'
gem 'rspec', '3.8.0'
gem 'rspec-retry'
gem 'rake', '12.3.3'
gem 'pry', '0.12.2'
gem 'httparty', '0.16.3'
gem 'report_builder', '1.8'
gem 'allure-cucumber'
gem 'site_prism'
gem 'capybara'